import type { Metadata } from 'next';
import { Geist, Geist_Mono, Roboto_Slab, Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/theme-provider';
import Header from '@/components/Header';
import StoreProvider from '@/store/StoreProvider';
import { Slide, ToastContainer } from 'react-toastify';

const robotoSlabHeading = Roboto_Slab({
	subsets: ['latin'],
	variable: '--font-heading',
});

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			suppressHydrationWarning
			lang='en'
			className={cn(
        				'h-full',
        				'scroll-smooth',
        				'antialiased',
        				geistSans.variable,
        				geistMono.variable,
        				'font-sans',
        				robotoSlabHeading.variable,
        				'font-sans',
        				'font-sans',
        			 "font-sans", inter.variable)}>
			<body
				className={`
					min-h-screen
					antialiased 
					font-sans
					bg-background 
					text-foreground
					selection:bg-primary/20
        	`}>
				{' '}
				<StoreProvider>
					<ThemeProvider
						attribute='class' // * Uses class-based theme switching
						defaultTheme='system' // * Respects user's system preference
						enableSystem // * Enables system theme detection
						disableTransitionOnChange // * Prevents flash during theme changes
						storageKey='app-theme' // * Custom storage key for theme persistence
					>
						{/* ! APP STRUCTURE */}
						<div className='flex min-h-screen flex-col'>
							{/* ? Header with consistent height */}
							<Header className='h-[20%] shrink-0' />{' '}
							{/* * Changed from vh to fixed height for consistency */}
							{/* ? Main content area with proper spacing */}
							<main className='flex-1 h-[79%] overflow-hidden'>
								{' '}
								{children}
								<ToastContainer
									position='bottom-right'
									autoClose={1500}
									hideProgressBar={false}
									newestOnTop={false}
									closeOnClick={true}
									rtl={false}
									pauseOnFocusLoss
									draggable
									pauseOnHover={false}
									theme='dark'
									transition={Slide}
								/>
							</main>
							{/* TODO: Add footer component if needed */}
							{/* <Footer className="shrink-0" /> */}
						</div>
					</ThemeProvider>
				</StoreProvider>
			</body>
		</html>
	);
}
