import type { Metadata } from 'next';
import { Geist, Geist_Mono, Roboto_Slab, Inter, Roboto_Mono, Plus_Jakarta_Sans, Fredoka, Sniglet, Urbanist, DM_Sans, JetBrains_Mono, Share_Tech_Mono } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/theme-provider';
import Header from '@/components/Header';
import StoreProvider from '@/store/StoreProvider';
import { Slide, ToastContainer } from 'react-toastify';


// Initialize fonts and assign them CSS variables
const inter = Inter({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-inter',
}); const robotoMono = Roboto_Mono({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-roboto-mono',
}); const robotoSlabHeading = Roboto_Slab({
	subsets: ['latin'],
	variable: '--font-heading',
}); const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
}); const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

//! Fonts
//? 🎮 Gamified & Rounded (Headers & Badges)
const fredoka = Fredoka({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700"],
	variable: "--font-badges",
});
const sniglet = Sniglet({
	subsets: ["latin"],
	weight: ["400", "800"],
	variable: "--font-heading",
});
//? 📱 Modern & Minimalist UI (Syllabus & Navigation)
const plusJakartaSans = Plus_Jakarta_Sans({
	subsets: ["latin"],
	weight: ["400", "500", "700", "200", "300", "600", "800"],
	variable: "--font-content-primary",
});
const urbanist = Urbanist({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	variable: "--font-content-secondary",
});
const DMSans = DM_Sans({
	subsets: ["latin"],
	weight: ["400", "500", "700", "200", "300", "600", "800", "100", "900"],
	variable: "--font-navigation",
});
//? ⏱️ Monospaced (Pomodoro Timer & Clock)
const jetBrainsMono = JetBrains_Mono({
	subsets: ["latin"],
	weight: ["400", "500", "700", "200", "300", "600", "800", "100"],
	variable: "--font-pomodoro",
});
const shareTechMono = Share_Tech_Mono({
	subsets: ["latin"],
	weight: ["400"],
	variable: "--font-clock",
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			suppressHydrationWarning
			lang='en'
			className={cn(
				'h-full w-full',
				'scroll-smooth',
				'antialiased',
				"[&::-webkit-scrollbar]:w-1 [&::-webkit-scrollbar-thumb]:bg-slate-300",
				geistSans.variable,
				geistMono.variable,
				robotoSlabHeading.variable,
				robotoMono.variable,
				inter.variable,
				plusJakartaSans.variable,
				fredoka.variable,
				sniglet.variable,
				urbanist.variable,
				DMSans.variable,
				jetBrainsMono.variable,
				shareTechMono.variable
			)}>
			<body
				className={cn(`
					min-h-screen
					antialiased 
					bg-background
					text-foreground
					selection:bg-primary/20
        	`,
					"font-content-primary",
					"[&::-webkit-scrollbar]:w-1 [&::-webkit-scrollbar-thumb]:bg-slate-300",
				)}>
				{' '}
				<StoreProvider>
					<ThemeProvider
						attribute='class' // * Uses class-based theme switching
						defaultTheme='system' // * Respects user's system preference
						enableSystem // * Enables system theme detection
						disableTransitionOnChange // * Prevents flash during theme changes
						storageKey='app-theme' // * Custom storage key for theme persistence
					>
						{/* ? Header with consistent height */}
						<Header className='h-[5.8vh] shrink-0' />{' '}
						{/* * Changed from vh to fixed height for consistency */}
						{/* ? Main content area with proper spacing */}
						<main className='h-[94.2vh] overflow-hidden'>
							{' '}
							{children}
							<ToastContainer
								position='bottom-right'
								autoClose={1500}
								hideProgressBar={false}
								newestOnTop={false}
								closeOnClick={true}
								rtl={false}
								pauseOnFocusLoss
								draggable
								pauseOnHover={false}
								theme='dark'
								transition={Slide}
							/>
						</main>
						{/* TODO: Add footer component if needed */}
						{/* <Footer className="shrink-0" /> */}
					</ThemeProvider>
				</StoreProvider>
			</body>
		</html>
	);
}
